name: CI

on:
  push:
    branches: [ fourteen ]
  pull_request:
    branches: [ fourteen ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build_flags: "-Dtarget=x86_64-linux"
          - os: macos-latest
          - os: windows-latest
          - os: ubuntu-24.04-arm
            build_flags: "-Dtarget=aarch64-linux"

    steps:
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Pacific/Honolulu"
          timezoneMacos: "Pacific/Honolulu"
          timezoneWindows: "Hawaiian Standard Time"
      
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential libc6-dev clang

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: "0.14.0-dev.3187+d4c85079c"

      - name: Build project
        run: zig build ${{ matrix.build_flags }} -Doptimize=ReleaseSmall

      - name: Run tests
        run: zig build test --summary all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpmf-${{ runner.os }}-${{ runner.arch }}
          path: |
            zig-out/bin/zig-gpmf*
