name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with ${{ matrix.zig_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        zig_version: ["0.14.1", "master"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest", "ubuntu-24.04-arm"]

    steps:
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Pacific/Honolulu"
          timezoneMacos: "Pacific/Honolulu"
          timezoneWindows: "Hawaiian Standard Time"
      
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential libc6-dev clang

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig_version }}

      - name: Build project
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            zig build -Dtarget=x86_64-linux -Doptimize=ReleaseSmall
          elif [[ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]]; then
            zig build -Dtarget=aarch64-linux -Doptimize=ReleaseSmall
          else
            zig build -Doptimize=ReleaseSmall
          fi

      - name: Run tests
        run: zig build test --summary all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpmf-${{ runner.os }}-${{ matrix.zig_version }}-${{ runner.arch }}
          path: |
            zig-out/bin/zig-gpmf*
